#!/bin/bash

LOG="/opt/security-system/tuya-bridge/cctv-cloudflare.log"
URL_FILE="/opt/security-system/tuya-bridge/cctv_public_url.txt"

rm -f "$LOG"

cloudflared tunnel \
  --url http://192.168.1.140:8889 \
  2>&1 | tee "$LOG" &

CFPID=$!

echo "Menunggu URL Cloudflare..."

while true; do

    URL=$(grep -oE 'https://[A-Za-z0-9-]+\.trycloudflare\.com' "$LOG" | tail -1)

    if [ -n "$URL" ]; then

        echo "$URL" > "$URL_FILE"

        echo "CCTV PUBLIC URL:"
        echo "$URL"

        break
    fi

    sleep 1

done

wait "$CFPID"	
